#!/bin/bash

case "$1" in
"adapter")
    # we need something different in order to pass the classpath of the current project
    # you must specify: appClassName (extends AdapterApp class) , cluster name, output stream name
    # current syntax is not yet straightforward:
    # example : ./s4 adapter -cluster=c1 -appClass=org.apache.s4.example.twitter.TwitterInputAdapter -p=s4.adapter.output.stream:s1
        shift 1
        $S4_HOME/gradlew cp
        java -cp `cat classpath.txt` org.apache.s4.core.Main $@
;;
*)
        echo "calling referenced s4 script : $S4_HOME/s4"
        (cd $S4_HOME && $S4_HOME/s4 $@)
;;
esac
